site_name: django-ai-assistant
site_description: Implement powerful AI assistants using Django

repo_name: vintasoftware/django-ai-assistant
repo_url: https://github.com/vintasoftware/django-ai-assistant/
edit_uri: blob/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

copyright: <a href="https://www.vintasoftware.com">Vinta Software</a>

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true
  - attr_list

nav:
  - Home:
    - Overview: index.md
  - Usage:
    - Get Started: get-started.md
    - Tutorial: tutorial.md
  - Reference:
    - helpers.assistants: assistants-ref.md
    - helpers.use_cases: use-cases-ref.md
  - Contributing: contributing.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_members_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            modernize_annotations: true
